<?
/*
 * Created on Nov 4, 2559
 * Created by Mark Libkuman
 * libkuman@openflows.com
 * www.openflows.com
 * 
 * Created for Manhattan Neighborhood Network
 */

function ac_report_init() {
	
  module_load_include('inc', 'ac_report', 'includes/ac_report.cache_tables');
  module_load_include('inc', 'ac_report', 'includes/ac_report.config');
  module_load_include('inc', 'ac_report', 'includes/ac_report.db_get');
  module_load_include('inc', 'ac_report', 'includes/ac_report.form');
  module_load_include('inc', 'ac_report', 'includes/ac_report.menu');
  module_load_include('inc', 'ac_report', 'includes/ac_report.misc');
  module_load_include('inc', 'ac_report', 'includes/ac_report.stored_procedures');
  module_load_include('inc', 'ac_report', 'includes/ac_report.synch_form');
  module_load_include('inc', 'ac_report', 'includes/ac_report.views');

}

